## NumPy Basics — 1D, 2D, 3D Arrays 

In [1]:
import numpy as np
print(np.__version__)

2.5.2


In [2]:
array_1d = np.arange(1, 6)
array_2d = np.arange(1, 7).reshape(2, 3)

print("1D:", array_1d, "| Shape:", array_1d.shape, "| Size:", array_1d.size, "| dtype:", array_1d.dtype)
print("2D:", array_2d.tolist(), "| Shape:", array_2d.shape, "| Size:", array_2d.size, "| dtype:", array_2d.dtype)

float_array = np.arange(1, 4, dtype=float)
print("Float array:", float_array, "| dtype:", float_array.dtype)

1D: [1 2 3 4 5] | Shape: (5,) | Size: 5 | dtype: int64
2D: [[1, 2, 3], [4, 5, 6]] | Shape: (2, 3) | Size: 6 | dtype: int64
Float array: [1. 2. 3.] | dtype: float64


In [3]:
# 1D: this week's temperatures (reuse Day 4's values)
weekly_temps = np.array([72, 74, 76, 80, 82, 78, 75])
print("Weekly temps:", weekly_temps)

# 2D: shape (2,5), values 1-10 chosen by us
grid = np.array([[1, 3, 5, 7, 9],
                  [2, 4, 6, 8, 10]])
print("2D grid:\n", grid, "| Shape:", grid.shape)

# 3D: a tiny 9-pixel "image" — let's make it 3x3 pixels, each with R,G,B (valid 0-255)
pixel_image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]],
    [[128, 128, 128], [255, 255, 255], [0, 0, 0]]
])
print("3D pixel array shape:", pixel_image.shape)

Weekly temps: [72 74 76 80 82 78 75]
2D grid:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]] | Shape: (2, 5)
3D pixel array shape: (3, 3, 3)


In [4]:
arr = np.arange(1, 11)  # 10 elements: 1-10
print("5th element:", arr[4])          # index 4 = 5th element
print("3rd to 8th:", arr[2:8])          # index 2 to 7

random_arr = np.random.randint(10, 50, 6)
print("Random array:", random_arr)
print("Greater than 30:", random_arr[random_arr > 30])
print("2nd, 4th, 6th elements:", random_arr[[1, 3, 5]])


5th element: 5
3rd to 8th: [3 4 5 6 7 8]
Random array: [28 29 14 11 13 17]
Greater than 30: []
2nd, 4th, 6th elements: [29 11 17]


In [5]:
# 1. Change the 5th element to 50
arr2 = np.arange(1, 11)
arr2[4] = 50
print("After change:", arr2)

# 2. Negate elements from index 3 to 7
arr2[3:8] = -arr2[3:8]
print("After negating 3-7:", arr2)

# 3. Boolean modification: set values > 50 to -1
rand20 = np.random.randint(1, 100, 20)
rand20[rand20 > 50] = -1
print("Random 20, >50 set to -1:", rand20)

# 4. Double the diagonal of a 5x5 array
grid5 = np.arange(1, 26).reshape(5, 5)
print("Before:\n", grid5)
diag_indices = np.arange(5)
grid5[diag_indices, diag_indices] = grid5[diag_indices, diag_indices] * 2
print("After doubling diagonal:\n", grid5)

# 5. Slicing creates a VIEW, not a copy
arr3 = np.arange(1, 11)
sub = arr3[2:5]
sub[0] = 999
print("Original array after modifying slice:", arr3)

After change: [ 1  2  3  4 50  6  7  8  9 10]
After negating 3-7: [  1   2   3  -4 -50  -6  -7  -8   9  10]
Random 20, >50 set to -1: [-1  7 18 -1 -1 -1 34 -1 -1 -1 10  8 -1 -1  6 -1 20 39 18 47]
Before:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
After doubling diagonal:
 [[ 2  2  3  4  5]
 [ 6 14  8  9 10]
 [11 12 26 14 15]
 [16 17 18 38 20]
 [21 22 23 24 50]]
Original array after modifying slice: [  1   2 999   4   5   6   7   8   9  10]
