In [1]:
import numpy as np

# Exercise 1: 1D array 0-9
ex1 = np.arange(10)
print(ex1)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
ex2 = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print(ex2)

[3 2 0 1 2]


In [3]:
ex3 = np.arange(1, 10).reshape(3, 3)
print(ex3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ex4 = np.random.rand(4, 5)
print(ex4)

[[0.65137239 0.48959013 0.11543596 0.20922117 0.19221262]
 [0.52012653 0.60840315 0.12259333 0.41676487 0.3429178 ]
 [0.22856937 0.59188069 0.6471961  0.85588211 0.57772564]
 [0.72611076 0.88942138 0.6296439  0.11484584 0.42172458]]


In [5]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
ex5 = array[1, :]
print(ex5)

[20 21 22 23 24]


In [6]:
ex6 = np.arange(10)[::-1]
print(ex6)

[9 8 7 6 5 4 3 2 1 0]


In [7]:
ex7 = np.eye(4)
print(ex7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
data = np.arange(0, 10)
print(f"Sum: {data.sum()}, Average: {data.mean()}")

Sum: 45, Average: 4.5


In [9]:
ex9 = np.arange(1, 21).reshape(4, 5)
print(ex9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
arr10 = np.arange(0, 10)
ex10 = arr10[arr10 % 2 != 0]
print(ex10)

[1 3 5 7 9]
